// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhAGHv7tv4IG0IAvKERjAdHwR4BLZ8w8U',
    appId: '1:870173465729:web:d7dddfd9b83b8d0a9c4180',
    messagingSenderId: '870173465729',
    projectId: 'homeworks-92c4c',
    authDomain: 'homeworks-92c4c.firebaseapp.com',
    storageBucket: 'homeworks-92c4c.appspot.com',
    measurementId: 'G-CF9MPMEC8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKYTQ6LpeEbuNPjOf1t6MbxsP6s6TeU9I',
    appId: '1:870173465729:android:7c78cf0af67a98139c4180',
    messagingSenderId: '870173465729',
    projectId: 'homeworks-92c4c',
    storageBucket: 'homeworks-92c4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWE1Rozo6kiS7AvZ5zP0u2ahvqsio1LB4',
    appId: '1:870173465729:ios:6139bcba3c7ccad89c4180',
    messagingSenderId: '870173465729',
    projectId: 'homeworks-92c4c',
    storageBucket: 'homeworks-92c4c.appspot.com',
    iosClientId: '870173465729-4jhlcgkblth39pkugmsnao5c375bb7tq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWE1Rozo6kiS7AvZ5zP0u2ahvqsio1LB4',
    appId: '1:870173465729:ios:6139bcba3c7ccad89c4180',
    messagingSenderId: '870173465729',
    projectId: 'homeworks-92c4c',
    storageBucket: 'homeworks-92c4c.appspot.com',
    iosClientId: '870173465729-4jhlcgkblth39pkugmsnao5c375bb7tq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
